apiVersion: v1
kind: Pod
metadata:
  name: ubi-minimal
  namespace: app-test
spec:
  containers:
  - name: ubi-minimal
    command: ["/bin/bash", "-c", "sleep 86400"]
    image: registry.redhat.io/ubi9/ubi:latest
